---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    exclude_fingerprints:
    - 0e2874eb10b15f5d1fd91065e150d359 # numericality complexity
    - 1163ea15068f012682d37bf2f473d797 # range/rangeLength "duplication"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
